### ISSUE TITLE
only users i put the id will use the bot 

### ISSUE THREAD

**Issue by kaifsarkar123** [1999AZZAR/Palm-powered-telegram-bot#7]
i want that every user will able to use the is it possible

**Comment by 1999AZZAR** [comment]
It's not an issues, u can just simply remove the user check process and that all.

**Comment by 1999AZZAR** [comment]
> It's not an issues, u can just simply remove the user check process and that all.

Or if you want to, I can make u one that suite your need by donating to my bymeacoffee account and send me a WhatsApp message or dm me on my telegram (all of that on my profile)
